### ISSUE TITLE
Pebble Time Round compatibility

### ISSUE THREAD

**Issue by waaeel** [Fertogo/Pebble-workout-timer#108]
Hey,
I love your app, but now i bought a pebble time round.
Can you please add compatibility with the time round.

Thank you.

**Comment by Fertogo** [comment]
Hey @waaeel 
This is the same as #92 which I unfortunately won't be implementing since Pebble has shut down. You could add `chalk` to the `targetPlatforms` in `appinfo.json` and compile to get a version that will install on a time round. The screen layouts may not be optimal, but it should be usable.

**Comment by waaeel** [comment]
Thanks , I will try
